site:
  id: "site"
  instagramEstudio: "https://www.instagram.com/proyecto.s3/"
  instagramObjeto: "https://www.instagram.com/object.s3/"
  whatsappNumero: "5491140332171"
  email: "proyecto.s3object@gmail.com"
